# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import safe_entry_pb2 as safe__entry__pb2


class Safe_EntryStub(object):
    """The safe entry service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check_In = channel.unary_unary(
                '/Safe_Entry.Safe_Entry/Check_In',
                request_serializer=safe__entry__pb2.Check_In_Request.SerializeToString,
                response_deserializer=safe__entry__pb2.Check_In_Reply.FromString,
                )


class Safe_EntryServicer(object):
    """The safe entry service definition.
    """

    def Check_In(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Safe_EntryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check_In': grpc.unary_unary_rpc_method_handler(
                    servicer.Check_In,
                    request_deserializer=safe__entry__pb2.Check_In_Request.FromString,
                    response_serializer=safe__entry__pb2.Check_In_Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Safe_Entry.Safe_Entry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Safe_Entry(object):
    """The safe entry service definition.
    """

    @staticmethod
    def Check_In(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Safe_Entry.Safe_Entry/Check_In',
            safe__entry__pb2.Check_In_Request.SerializeToString,
            safe__entry__pb2.Check_In_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
